//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoC2017.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AoC2017.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsddbi (61)
        ///nqtowev (11)
        ///xwohr (82)
        ///flejt (36)
        ///idwpug (54)
        ///uoxzkp (51)
        ///choeijs (54)
        ///gmsjkn (65)
        ///txszqu (687) -&gt; mvjqmad, lwqlyjq, jlgnsu
        ///zhlfdac (15)
        ///htouwcr (74)
        ///vlbsr (56)
        ///titbn (9)
        ///bvrpb (86)
        ///wuwjp (54)
        ///umnqkb (160) -&gt; nbrvl, bcmbao, vfimqtl
        ///uwnml (29)
        ///cdvhmy (42)
        ///xghhu (306) -&gt; molth, atqewc
        ///vcvayah (71)
        ///fujwb (187) -&gt; tyjyc, xyemll
        ///zqnjd (91) -&gt; jxsmuey, uelnii, vcwezm, uxnwtp
        ///wphtnvm (72)
        ///xgihtsx (15)
        ///fwvvidu (80)
        ///lonwb (1656) -&gt; rydrp, mgyixhn, cjhtxo
        ///qyasuw (41)
        ///vbvug (6)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day7Input {
            get {
                return ResourceManager.GetString("Day7Input", resourceCulture);
            }
        }
    }
}
